# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
aliases:
    - &restore_gem_cache
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

    - &npm_install
        name: Install Dependencies
        command: npm install

    - &save_gem_cache
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - &dependencies
        - checkout
        - restore_cache: *restore_gem_cache
        - run: *npm_install
        - save_cache: *save_gem_cache

    - &testing_command
      - checkout
      - run: npm run test

    # Requirement groups
    - &deps
        - "Dependencies"

    # Build environments
    - &deploy_environment
        docker:
          - image: circleci/node:8.16.0
        working_directory: ~/repo

version: 2
workflows:
    version: 2
    master:
        jobs:
          - "Dependencies"
          - "Testing First Command":
              requires: *deps
          - "Testing Second Command":
              requires: *deps
          - "Testing Third Command":
              requires: *deps

jobs:
  "Dependencies":
    <<: *deploy_environment
    steps: *dependencies
  
  "Testing First Command":
    <<: *deploy_environment
    steps: *testing_command
  
  "Testing Second Command":
    <<: *deploy_environment
    steps: *testing_command
  
  "Testing Third Command":
    <<: *deploy_environment
    steps: *testing_command